# Generated by Django 5.2.11 on 2026-02-28 04:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='device',
            name='audio_url',
        ),
        migrations.RemoveField(
            model_name='device',
            name='photo_url',
        ),
        migrations.AddField(
            model_name='device',
            name='audio',
            field=models.FileField(blank=True, null=True, upload_to='devices/audio/'),
        ),
        migrations.AddField(
            model_name='device',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='devices/photos/'),
        ),
    ]
