# Generated by Django 5.2.11 on 2026-02-28 04:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0002_add_photo_audio_files'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='custom_fields',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
