# Generated by Django 5.2.11 on 2026-02-28 04:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0003_add_custom_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='emergency_contacts',
            field=models.JSONField(default=list),
        ),
    ]
